// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBqnOlZeZ-0wJMi8f4JZ-eXJv1Qrzg3CU',
    appId: '1:21903278566:web:0b7b5c22687ca0bc091627',
    messagingSenderId: '21903278566',
    projectId: 'newtest-ad138',
    authDomain: 'newtest-ad138.firebaseapp.com',
    storageBucket: 'newtest-ad138.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6mU2DQAL1jaB3KR30xPQXBCUF0Y-F3Ds',
    appId: '1:21903278566:android:d3e8a66229ef4f4f091627',
    messagingSenderId: '21903278566',
    projectId: 'newtest-ad138',
    storageBucket: 'newtest-ad138.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFd1TaoaG6MUWCXLfFFb2c6v8vx_MgsAk',
    appId: '1:21903278566:ios:0442c7b615e2be7c091627',
    messagingSenderId: '21903278566',
    projectId: 'newtest-ad138',
    storageBucket: 'newtest-ad138.appspot.com',
    iosBundleId: 'com.example.aboditest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFd1TaoaG6MUWCXLfFFb2c6v8vx_MgsAk',
    appId: '1:21903278566:ios:21719c8214d4bc1f091627',
    messagingSenderId: '21903278566',
    projectId: 'newtest-ad138',
    storageBucket: 'newtest-ad138.appspot.com',
    iosBundleId: 'com.example.aboditest.RunnerTests',
  );
}
